replicaCount: 1

serviceAccount:
  create: false

zookeeper:
  enabled: false

broker:
  replicaCount: 1

controller:
  replicaCount: 1

kraft:
  enabled: true
  clusterId: "1"

listeners:
  client:
    protocol: "PLAINTEXT"
  controller:
    protocol: "PLAINTEXT"

extraConfigYaml:
  "offsets.topic.replication.factor": "1"
  "default.replication.factor": "1"
  "confluent.metrics.reporter.topic.replicas": "1"
  "transaction.state.log.replication.factor": "1"
  "transaction.state.log.min.isr": "1"

metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
