global:
  postgresql:
    auth:
      postgresPassword: ocYVfqJTBRqCBwdO8vAb

configOverrides:
  extend_timeout: |
    SUPERSET_WEBSERVER_TIMEOUT = 300
  vs_override: |
    FEATURE_FLAGS = {
      "ENABLE_TEMPLATE_PROCESSING": True
    }
  secret: |
    SECRET_KEY = 'AVOIBiGEMKyd594s5Ndh4MBFYG9Zfx0tytsoC7O++A0jPqjm6dGpZ3T2'

bootstrapScript: |
  #!/bin/bash
  pip install clickhouse-connect &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

extraConfigs:
  import_datasources.yaml: |
    databases:
    - allow_file_upload: true
      allow_ctas: true
      allow_cvas: true
      database_name: default
      extra: "{\r\n    \"metadata_params\": {},\r\n    \"engine_params\": {},\r\n    \"\
        metadata_cache_timeout\": {},\r\n    \"schemas_allowed_for_file_upload\": []\r\n\
        }"
      sqlalchemy_uri: clickhousedb://default:default@clickhouse.clickhouse.svc.cluster.local/default
      tables: []
