datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-operated.monitoring.svc.cluster.local:9090
        version: 1
        editable: true
        isDefault: true
      - name: Alertmanager
        uid: alertmanager
        type: alertmanager
        access: proxy
        orgId: 1
        url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
        version: 1
        editable: true
        jsonData:
          implementation: prometheus