// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.2
// source: k8s/clickhouse/trade.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecType     string  `protobuf:"bytes,2,opt,name=secType,proto3" json:"secType,omitempty"`
	Last        float64 `protobuf:"fixed64,3,opt,name=last,proto3" json:"last,omitempty"`
	TradingTime string  `protobuf:"bytes,4,opt,name=tradingTime,proto3" json:"tradingTime,omitempty"`
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_k8s_clickhouse_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_k8s_clickhouse_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_k8s_clickhouse_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetSecType() string {
	if x != nil {
		return x.SecType
	}
	return ""
}

func (x *Trade) GetLast() float64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *Trade) GetTradingTime() string {
	if x != nil {
		return x.TradingTime
	}
	return ""
}

var File_k8s_clickhouse_trade_proto protoreflect.FileDescriptor

var file_k8s_clickhouse_trade_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6b, 0x38, 0x73, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x05,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c,
	0x61, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_k8s_clickhouse_trade_proto_rawDescOnce sync.Once
	file_k8s_clickhouse_trade_proto_rawDescData = file_k8s_clickhouse_trade_proto_rawDesc
)

func file_k8s_clickhouse_trade_proto_rawDescGZIP() []byte {
	file_k8s_clickhouse_trade_proto_rawDescOnce.Do(func() {
		file_k8s_clickhouse_trade_proto_rawDescData = protoimpl.X.CompressGZIP(file_k8s_clickhouse_trade_proto_rawDescData)
	})
	return file_k8s_clickhouse_trade_proto_rawDescData
}

var file_k8s_clickhouse_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_k8s_clickhouse_trade_proto_goTypes = []any{
	(*Trade)(nil), // 0: Trade
}
var file_k8s_clickhouse_trade_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_k8s_clickhouse_trade_proto_init() }
func file_k8s_clickhouse_trade_proto_init() {
	if File_k8s_clickhouse_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_k8s_clickhouse_trade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_k8s_clickhouse_trade_proto_goTypes,
		DependencyIndexes: file_k8s_clickhouse_trade_proto_depIdxs,
		MessageInfos:      file_k8s_clickhouse_trade_proto_msgTypes,
	}.Build()
	File_k8s_clickhouse_trade_proto = out.File
	file_k8s_clickhouse_trade_proto_rawDesc = nil
	file_k8s_clickhouse_trade_proto_goTypes = nil
	file_k8s_clickhouse_trade_proto_depIdxs = nil
}
